export const REGISTER_STUDENT = "REGISTER_STUDENT";
export const GET_STUDENT_REGISTRATION_DETAILS =
  "GET_STUDENT_REGISTRATION_DETAILS";
export const USER_DETAILS = "USER_DETAILS";

export const SET_TOKEN = "SET_TOKEN";
