export const REGISTER_STUDENT = "REGISTER_STUDENT";
export const GET_STUDENT_REGISTRATION_DETAILS =
  "GET_STUDENT_REGISTRATION_DETAILS";
export const USER_DETAILS = "USER_DETAILS";
export const APPLIED_TEACHER_DETAILS = "APPLIED_TEACHER_DETAILS";
export const SET_LOGIN_FLAG = "SET_LOGIN_FLAG";
export const SET_TOKEN = "SET_TOKEN";
export const SET_STUDENT_DETAILS = "SET_STUDENT_DETAILS";
